# Generated by Django 5.2.5 on 2025-09-04 13:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, verbose_name='Resolution')),
                ('period_start', models.DateTimeField(help_text='Start of the aggregation period', verbose_name='Period Start')),
                ('period_end', models.DateTimeField(help_text='End of the aggregation period', verbose_name='Period End')),
                ('sales_count', models.PositiveIntegerField(default=0, help_text='Number of completed sales in this period', verbose_name='Sales Count')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of final_total for all sales in this period', max_digits=12, verbose_name='Total Revenue')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of cost of goods sold for all sales in this period', max_digits=12, verbose_name='Total Cost')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue minus total cost', max_digits=12, verbose_name='Total Profit')),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average revenue per sale in this period', max_digits=10, verbose_name='Average Sale Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-period_start', 'resolution'],
                'indexes': [models.Index(fields=['resolution', 'period_start'], name='reports_sal_resolut_a6f160_idx'), models.Index(fields=['resolution', '-period_start'], name='reports_sal_resolut_cc1f00_idx'), models.Index(fields=['period_start', 'period_end'], name='reports_sal_period__979a26_idx')],
                'unique_together': {('resolution', 'period_start')},
            },
        ),
    ]
