# Generated by Django 5.2.5 on 2025-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='مفتاح التخزين المؤقت')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الصلاحية')),
            ],
            options={
                'verbose_name': 'تخزين مؤقت للتحليلات',
                'verbose_name_plural': 'التخزين المؤقت للتحليلات',
                'indexes': [models.Index(fields=['cache_key'], name='analytics_a_cache_k_9a5fb4_idx'), models.Index(fields=['expires_at'], name='analytics_a_expires_4e35a3_idx')],
            },
        ),
    ]
