# Generated by Django 5.2.5 on 2025-08-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(help_text='اسم العميل بالعربية', max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, help_text='اسم العميل بالإنجليزية (اختياري)', max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('phone', models.CharField(blank=True, help_text='رقم هاتف العميل', max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('other', 'أخرى'), ('not_specified', 'غير محدد')], default='not_specified', max_length=20, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('notes', models.TextField(blank=True, help_text='أي ملاحظات إضافية عن العميل', verbose_name='ملاحظات')),
                ('is_placeholder', models.BooleanField(default=False, help_text="يُستخدم للعملاء الافتراضيين مثل 'فلان' و 'فلانة'", verbose_name='عميل وهمي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name_ar'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['name_ar'], name='customers_c_name_ar_c46c27_idx'), models.Index(fields=['gender'], name='customers_c_gender_987129_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
            },
        ),
    ]
