# Generated by Django 5.2.5 on 2025-09-06 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_customer_to_sale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البيع'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_sale_product'),
        ),
    ]
