# Generated by Django 5.2.5 on 2025-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_saleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم البيعة'),
        ),
    ]
